services:
  - type: web
    name: expense-tracker-backend
    env: ruby
    plan: free
    buildCommand: "cd backend/expense-tracker-api && bundle install"
    startCommand: "cd backend/expense-tracker-api && bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: expense-tracker
    plan: free